### ISSUE TITLE
INT-WIS Issue

### ISSUE THREAD

**Issue by Barrels23** [ReltivlyObjectv/MonsterBrewery#2]
When rendering a file, the spot for the Wisdom ability score displays the INT ability score instead. The two are different while building the monster, however.
![int-wis issue](https://user-images.githubusercontent.com/22619725/29629426-637a37da-87fe-11e7-9abf-bcec565ad3c0.png)

**Comment by ReltivlyObjectv** [comment]
Thank you for bringing this to my attention! It has been fixed in version 1.1
<img width="294" alt="screen shot 2017-08-25 at 8 09 44 pm" src="https://user-images.githubusercontent.com/2250937/29738182-621a10e8-89d1-11e7-82bc-576b74d63470.png">
